//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 05:28:38 PM MSK 
//


package com.study.parser.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CertificateInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="certification-enterprise" type="{http://www.entity.parser.study.com}CertificationEnterprise"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cert-number" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="expiration-date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateInfo", propOrder = {
    "certificationEnterprise"
})
public class CertificateInfo {

    @XmlElement(name = "certification-enterprise", required = true)
    protected CertificationEnterprise certificationEnterprise;
    @XmlAttribute(name = "cert-number", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String certNumber;
    @XmlAttribute(name = "expiration-date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expirationDate;

    /**
     * Gets the value of the certificationEnterprise property.
     * 
     * @return
     *     possible object is
     *     {@link CertificationEnterprise }
     *     
     */
    public CertificationEnterprise getCertificationEnterprise() {
        return certificationEnterprise;
    }

    /**
     * Sets the value of the certificationEnterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificationEnterprise }
     *     
     */
    public void setCertificationEnterprise(CertificationEnterprise value) {
        this.certificationEnterprise = value;
    }

    /**
     * Gets the value of the certNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertNumber() {
        return certNumber;
    }

    /**
     * Sets the value of the certNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertNumber(String value) {
        this.certNumber = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

}
