//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 05:28:38 PM MSK 
//


package com.study.parser.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dosage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dosage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dosage-amount" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="dosage-periodicity" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dosage")
public class Dosage {

    @XmlAttribute(name = "dosage-amount", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dosageAmount;
    @XmlAttribute(name = "dosage-periodicity")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dosagePeriodicity;

    /**
     * Gets the value of the dosageAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDosageAmount() {
        return dosageAmount;
    }

    /**
     * Sets the value of the dosageAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDosageAmount(BigInteger value) {
        this.dosageAmount = value;
    }

    /**
     * Gets the value of the dosagePeriodicity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDosagePeriodicity() {
        return dosagePeriodicity;
    }

    /**
     * Sets the value of the dosagePeriodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDosagePeriodicity(BigInteger value) {
        this.dosagePeriodicity = value;
    }

}
