//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 05:28:38 PM MSK 
//


package com.study.parser.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Medicine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Medicine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="certification-info" type="{http://www.entity.parser.study.com}CertificateInfo"/>
 *         &lt;element name="package" type="{http://www.entity.parser.study.com}Package"/>
 *         &lt;element name="dosage" type="{http://www.entity.parser.study.com}Dosage"/>
 *       &lt;/sequence>
 *       &lt;attribute name="medicine-id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="medicine-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pharm" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="group" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="painkiller"/>
 *             &lt;enumeration value="antibiotic"/>
 *             &lt;enumeration value="vitamin"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="version">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="tablet"/>
 *             &lt;enumeration value="capsule"/>
 *             &lt;enumeration value="powder"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Medicine", propOrder = {
    "certificationInfo",
    "_package",
    "dosage"
})
@XmlSeeAlso({
    DomesticMedicine.class,
    ForeignMedicine.class
})
public class Medicine {

    @XmlElement(name = "certification-info", required = true)
    protected CertificateInfo certificationInfo;
    @XmlElement(name = "package", required = true)
    protected Package _package;
    @XmlElement(required = true)
    protected Dosage dosage;
    @XmlAttribute(name = "medicine-id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String medicineId;
    @XmlAttribute(name = "medicine-name", required = true)
    protected String medicineName;
    @XmlAttribute(name = "pharm", required = true)
    protected String pharm;
    @XmlAttribute(name = "group", required = true)
    protected String group;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the certificationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateInfo }
     *     
     */
    public CertificateInfo getCertificationInfo() {
        return certificationInfo;
    }

    /**
     * Sets the value of the certificationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateInfo }
     *     
     */
    public void setCertificationInfo(CertificateInfo value) {
        this.certificationInfo = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link Package }
     *     
     */
    public Package getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link Package }
     *     
     */
    public void setPackage(Package value) {
        this._package = value;
    }

    /**
     * Gets the value of the dosage property.
     * 
     * @return
     *     possible object is
     *     {@link Dosage }
     *     
     */
    public Dosage getDosage() {
        return dosage;
    }

    /**
     * Sets the value of the dosage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dosage }
     *     
     */
    public void setDosage(Dosage value) {
        this.dosage = value;
    }

    /**
     * Gets the value of the medicineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicineId() {
        return medicineId;
    }

    /**
     * Sets the value of the medicineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicineId(String value) {
        this.medicineId = value;
    }

    /**
     * Gets the value of the medicineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicineName() {
        return medicineName;
    }

    /**
     * Sets the value of the medicineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicineName(String value) {
        this.medicineName = value;
    }

    /**
     * Gets the value of the pharm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharm() {
        return pharm;
    }

    /**
     * Sets the value of the pharm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharm(String value) {
        this.pharm = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
